import React from 'react'

const TOPICS = [
  {
    term: 'Context-Free Grammar (CFG)',
    body:
      'A set of production rules of the form A → α, where A is a non-terminal and α is a string of terminals and/or non-terminals. It defines the syntax of a language.',
  },
  {
    term: 'Terminal',
    body: 'A symbol that appears in the final strings generated by the grammar — it cannot be expanded further (e.g. id, +, ().',
  },
  {
    term: 'Non-terminal',
    body: 'A symbol that can be expanded into a sequence of terminals and non-terminals via a production rule (e.g. E, T, F).',
  },
  {
    term: 'Production',
    body: "A rewrite rule A → α describing how a non-terminal A can be replaced by a string α.",
  },
  {
    term: 'Epsilon (ε)',
    body: 'Represents the empty string — a production A → ε means A can derive nothing at all.',
  },
  {
    term: 'FIRST(α)',
    body: 'The set of terminals that can appear as the first symbol of some string derived from α. If α can derive ε, then ε ∈ FIRST(α).',
  },
  {
    term: 'FOLLOW(A)',
    body: 'The set of terminals that can appear immediately to the right of A in some sentential form, including $ if A can be the last symbol of the input.',
  },
  {
    term: 'Left Recursion',
    body: "A production of the form A → Aα causes a top-down parser to recurse infinitely without consuming input. It must be eliminated before LL(1) parsing.",
  },
  {
    term: 'Left Factoring',
    body: 'A transformation applied when two or more alternatives of a non-terminal share a common prefix, which would otherwise prevent a parser from deciding which alternative to use with only one lookahead token.',
  },
  {
    term: 'LL(1)',
    body: "A grammar that can be parsed top-down (Left-to-right scan, Leftmost derivation) using only 1 token of lookahead, with no backtracking.",
  },
  {
    term: 'Predictive Parsing',
    body: 'Table-driven parsing that uses the LL(1) table to deterministically decide, at every step, which production to apply based on the current stack top and lookahead token.',
  },
  {
    term: 'Parsing Table',
    body: 'A 2D table M[NonTerminal, Terminal] that stores which production to apply. Built from FIRST and FOLLOW sets of the grammar.',
  },
  {
    term: 'Parse Tree',
    body: "A tree representation of a derivation, showing how the start symbol is expanded step by step into the input string.",
  },
]

const VIVA = [
  ['What is a CFG?', 'A 4-tuple (N, Σ, P, S) of non-terminals, terminals, productions, and a start symbol that generates a context-free language.'],
  ['What is FIRST?', 'The set of terminals that can begin strings derivable from a grammar symbol or symbol sequence.'],
  ['What is FOLLOW?', 'The set of terminals that can immediately follow a non-terminal in some derivation.'],
  ['Why is $ placed in FOLLOW(start)?', 'To signal end-of-input; the parser accepts only when the stack and remaining input are both exhausted together.'],
  ['What is epsilon?', 'The empty string — used when a non-terminal can derive nothing.'],
  ['Why is left recursion a problem for LL(1)?', "A top-down parser would try to expand A → Aα forever without consuming any input, causing infinite recursion."],
  ['How is left recursion eliminated?', 'A → Aα | β becomes A → βA\', A\' → αA\' | ε.'],
  ['What is left factoring?', 'Factoring out a shared prefix among a non-terminal\'s alternatives into a new non-terminal.'],
  ['Why is left factoring required?', "Without it, the parser can't decide which alternative to expand using only one lookahead token."],
  ['What does LL(1) mean?', 'Left-to-right scan, Leftmost derivation, 1 token of lookahead.'],
  ['How is the parsing table constructed?', 'For A → α, add A → α to M[A, a] for each a in FIRST(α); if ε ∈ FIRST(α), add it to M[A, b] for each b in FOLLOW(A).'],
  ['What is a FIRST/FIRST conflict?', 'Two productions of the same non-terminal have overlapping FIRST sets, so the parser cannot choose deterministically.'],
  ['What is a FIRST/FOLLOW conflict?', 'One alternative is nullable and its FOLLOW set overlaps with another alternative\'s FIRST set.'],
  ['Why recompute FIRST/FOLLOW after transformation?', "The original grammar's sets no longer correspond to the actual productions used by the parser once the grammar has been rewritten."],
  ['How does predictive parsing work?', 'A stack holds the current sentential form; at each step, the parser consults M[top, lookahead] to expand or match.'],
  ['What happens when a table cell is empty?', 'It signals a syntax error — no valid derivation exists for the current input.'],
  ['How does the parser handle an invalid token?', 'It reports the current stack, remaining input, the offending token, and the terminals that were expected.'],
  ['Difference between parse tree and AST?', 'A parse tree shows every grammar rule applied (including intermediate non-terminals); an AST abstracts away syntactic detail to keep only semantically meaningful structure.'],
  ['Difference between LL(1) and LR parsing?', 'LL(1) builds a leftmost derivation top-down with 1 lookahead; LR builds a rightmost derivation in reverse, bottom-up, and can handle a strictly larger class of grammars.'],
  ['Why use a stack?', 'It naturally models the pending, not-yet-expanded portion of the sentential form during a top-down derivation.'],
  ['Why is $ used?', 'As an explicit end-of-input marker so the parser can detect acceptance unambiguously.'],
  ['What are nullable non-terminals?', 'Non-terminals that can derive the empty string ε.'],
  ['How are indirect dependencies handled?', 'FIRST/FOLLOW use a fixed-point (worklist) algorithm, iterating until no set changes, which correctly propagates indirect dependencies.'],
  ['How is the start symbol selected?', "By default it's the first non-terminal declared; the user may override it explicitly."],
  ['What limitations does this implementation have?', 'It supports the standard immediate + ordered indirect left-recursion elimination algorithm; grammars needing more advanced restructuring outside that scope are reported, not silently mis-transformed.'],
]

export default function LearnTab() {
  return (
    <div className="space-y-6">
      <div className="bg-white border border-gray-200 rounded-xl p-5 transition-colors">
        <h3 className="text-sm font-bold text-gray-800 mb-3 uppercase tracking-wide">
          Core Concepts
        </h3>
        <div className="grid sm:grid-cols-2 gap-4">
          {TOPICS.map((t) => (
            <div key={t.term} className="border-l-2 border-indigo-500 pl-3">
              <p className="text-sm font-semibold text-indigo-700">{t.term}</p>
              <p className="text-xs text-gray-600 mt-0.5 leading-relaxed">{t.body}</p>
            </div>
          ))}
        </div>
      </div>

      <div className="bg-white border border-gray-200 rounded-xl p-5 transition-colors">
        <h3 className="text-sm font-bold text-gray-800 mb-3 uppercase tracking-wide">
          Viva Preparation & Q&A
        </h3>
        <div className="space-y-3">
          {VIVA.map(([q, a], i) => (
            <details
              key={i}
              className="border border-gray-200 bg-gray-50 hover:bg-gray-100 rounded-lg px-3.5 py-2.5 transition-colors group"
            >
              <summary className="text-sm font-semibold text-gray-800 cursor-pointer outline-none group-hover:text-indigo-700">
                {q}
              </summary>
              <p className="text-xs text-gray-700 mt-2 leading-relaxed pl-2 border-l border-indigo-500">
                {a}
              </p>
            </details>
          ))}
        </div>
      </div>
    </div>
  )
}

